### ISSUE TITLE
Webpack - Why does Webpack hate some .jpg(s)/.jpeg(s)?

### ISSUE THREAD

**Issue by sethborne** [RecursiveThinking/recursive_thinking_website#100]
Bye, Bye Porg.  Bye Bye!

**Comment by sethborne** [comment]
just that the porg_sq.jpeg doesn't load anymore.

we tried

porg_sq.jpg
porgsq.jpg
porgsq.png

none of them get included in the build

the odd thing is that only the porg_sq.jpeg is omitted.  the other .jpg
(banner.jpg) is included in the build just fine.

S

**Comment by MynockSpit** [comment]
Ah... yeah... that's b/c images in the images folder don't get imported automatically. They have to be 'used' somewhere. In this case, 'used' means it's either **referenced in the index.html file** or **imported into one of the .js files**. 

If you look in main.js, there's a bunch of imports for images. The only reason they exist is to tell webpack to bundle them.

**Comment by MynockSpit** [comment]
Actually, there's a strange behaviour we could hijack with webpack imports to import everything in the images folder...
