### ISSUE TITLE
UI - Edit Profile 'Years of Experience' portion wrong placeholders

### ISSUE THREAD

**Issue by amnevins** [RecursiveThinking/recursive_thinking_website#15]
In Edit Profile 'Years of Experience' portion wrong placeholders say 'github url', also this could use some tweaking as these three inputs look really crowded

**Comment by MynockSpit** [comment]
@sethborne -- Fix this? Which commit?

**Comment by sethborne** [comment]
up.  sorry - got to busy commenting on issues.  :(

**Comment by MynockSpit** [comment]
No worries! Just checking! 😃
