### ISSUE TITLE
UI - Upcoming Lessons attending buttons are not selectable.

### ISSUE THREAD

**Issue by amnevins** [RecursiveThinking/recursive_thinking_website#17]
Attending Buttons should behave more like Click to Vote buttons on vote for lessons page.

**Comment by sethborne** [comment]
reopened this issue.

Attending Button inconsistent with mockup,

Also - previous fix for:

UI - Upcoming Lessons should have cursor pointer #18

seems to have been removed.

**Comment by MynockSpit** [comment]
Confirmed this fixes it.
