### ISSUE TITLE
Safari - Doesnt support rel=import

### ISSUE THREAD

**Issue by amnevins** [RecursiveThinking/recursive_thinking_website#19]
Will have to do some concatenating of html webpack magic to put all templates in index.html.  They are doc frags so should not hold up loading of DOM. This will make us work on Safari.

**Comment by clayton-perszyk** [comment]
was looking into a polyfill, but didn't have any luck getting it to work

**Comment by MynockSpit** [comment]
Oh really? Where were you looking.

**Comment by MynockSpit** [comment]
So there's this: https://github.com/webcomponents/html-imports

Either we need to figure out how to get this to work, or re-think how we're doing our imports. (e.g. Maybe we should have a build step concatenate all the HTML files and only load one?)

**Comment by clayton-perszyk** [comment]
here's the one I was checking out: https://github.com/webcomponents/webcomponentsjs

**Comment by MynockSpit** [comment]
We're no longer using html imports so this shouldn't be an issue anymore.
