### ISSUE TITLE
UI - recursive directory - how to handle user id/profile routing when name is clicked.

### ISSUE THREAD

**Issue by sethborne** [RecursiveThinking/recursive_thinking_website#23]

**Comment by MynockSpit** [comment]
What's the definition of done on this issue? (If I were to take it, how would I know when it's complete?)

**Comment by sethborne** [comment]
I'd consider it done when you click a name in the recursive directory, and it goes to the viewProfile.html page, and the viewProfile.html page loads the correct (the one you clicked on)

(at least this is how I think this feature/page connection works)

I could probably help with this after the routing is complete (like filling in the template...)

**Comment by MynockSpit** [comment]
Appears complete.
