### ISSUE TITLE
LINK TO ZEPPELIN MOCKS

### ISSUE THREAD

**Issue by amnevins** [RecursiveThinking/recursive_thinking_website#33]
Here is the link to the mocks - https://app.zeplin.io/project/5a35b3271068e9760ef79fc6?ref=slack&sid=5a3ee1ed5ca05206888c0425&sid=5a3ee1f05e997d801451e1fe&sid=5a3ee1ed48ce3f4014319fdb

**Comment by MynockSpit** [comment]
Maybe this should go in the Readme?

**Comment by amnevins** [comment]
Lol yeah idk why i put it here

**Comment by MynockSpit** [comment]
https://github.com/RecursiveThinking/recursive_thinking_website/compare/390e972005c9...2db18f6712a2 adds mockup links to the readme.
