### ISSUE TITLE
explore editable divs in case textarea bug can't be fixed

### ISSUE THREAD

**Issue by sethborne** [RecursiveThinking/recursive_thinking_website#37]

**Comment by MynockSpit** [comment]
https://github.com/RecursiveThinking/recursive_thinking_website/commit/76c902a3390e32724d26ef441f579ab789e75850 fixes this issue. Still might be worth it to see if they work. (Probably will.)

**Comment by MynockSpit** [comment]
Just tested. `<div contenteditable="true"><slot name="mySlot"></slot></div>` will also work.
