### ISSUE TITLE
UI - homeScreen html - can have multiple modals open at the same time

### ISSUE THREAD

**Issue by sethborne** [RecursiveThinking/recursive_thinking_website#45]
Right now both the signup and login can be open at the same time.

perhaps a little killAllCurrentlyOpenModals() function should run before creating either modal?

**Comment by MynockSpit** [comment]
Sounds like a great idea! Maybe we provide an `openModal()` function (similar to how we have a `setUpPage()`) which would close (cancel) all other modals, then build the new one. That might be over-architected, though.
