### ISSUE TITLE
Convert dashboard html/js to a templater format

### ISSUE THREAD

**Issue by MynockSpit** [RecursiveThinking/recursive_thinking_website#5]
dashboard.html is already dynamic -- convert it to using templates for the HTML, and fill() those templates using a model. (see recursive_directory_model.js and recursiveDirectory.html for examples)

**Comment by amnevins** [comment]
Completed as per https://github.com/RecursiveThinking/recursive_thinking_website/commit/cea15a31f485d0c91ea53e1fffdd5be0c3913dd8
