### ISSUE TITLE
Layout Incorrect after visiting the Home Page

### ISSUE THREAD

**Issue by MynockSpit** [RecursiveThinking/recursive_thinking_website#55]
Repro:

1. Go the `dashboard`.
2. Go to the `home screen`.
3. Go back to the `dashboard`.
4. Observe the dashboard is **under** the sidebar.

Before:

<img width="1280" alt="screen shot 2018-03-02 at 7 17 13 pm" src="https://user-images.githubusercontent.com/5713867/36930028-60f73ef4-1e4e-11e8-8779-3d55b4792d46.png">

After:

<img width="1280" alt="screen shot 2018-03-02 at 7 17 24 pm" src="https://user-images.githubusercontent.com/5713867/36930030-694b5d4c-1e4e-11e8-843d-0963d30de972.png">

**Comment by sethborne** [comment]
^-- agreed!  Can we do #44?  Just have JS do the calcs of every fixed element on resize? Plz?

**Comment by MynockSpit** [comment]
I'd rather not. The positioning shouldn't be that horrendous once we finish #46.

**Comment by sethborne** [comment]
slightly less fubar'ed - #70

**Comment by AvsCode** [comment]
This issue seems to be resolved...

**Comment by MynockSpit** [comment]
Sure does.
