### ISSUE TITLE
HTML - change placeholder text in editProfile.html for Links:

### ISSUE THREAD

**Issue by sethborne** [RecursiveThinking/recursive_thinking_website#59]
Based on the userSchema:

GitHub/CodePen/LinkedIn/Portfolio should accept just the username for these sites

so change placeholder text to reflect this desired input, i.e.:

GitHub: [ Please enter GitHub Username ]

**Comment by kennh** [comment]
I changed the placeholders to reflect Please enter "website" Username.  On the Portfolio using a username did not make sense so I made it Please enter Portfolio URL.

**Comment by sethborne** [comment]
@kennh - sounds good and good catch on the Portfolio URL - closing this now.
