### ISSUE TITLE
General - GitHub Issues - Monitoring Issues

### ISSUE THREAD

**Issue by sethborne** [RecursiveThinking/recursive_thinking_website#61]
If I want to monitor the status on posted issues (like all FE issues), is there a better way to do this than just assigning myself to all of them?  (that way I can filter by assignee) <-- because this doesn't seem to be the best way to do it...

If anyone knows a better way, please let me know!

**Comment by sethborne** [comment]
maybe a frontend tag, then:

label:frontend in filter?

**Comment by MynockSpit** [comment]
Is your goal to have a view of all (or a subset) issues or notifications?

**Comment by sethborne** [comment]
yeah - so i just made a frontend tag - and I've been using the label:frontend in the filter bar

that way I have a handle on what frontend items are remaining to close out.  This system seems ok (much better than assigning myself to all of them!) but if there is a cleaner suggestion, I'd like to hear it

**Comment by MynockSpit** [comment]
Yeah, not sure there's a better system for viewing specific issues. If you wanted to receive notifications, you could go through the hassle of 'Subscribing' yourself to all of them, but that would not work for new issues. We already have a backend label, so frontend label makes sense.

**Comment by MynockSpit** [comment]
To help with this, we could make a new issue template that tells people to label their issues.

https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by MynockSpit** [comment]
@sethborne Closing this -- if you need it, feel free to reopen.
