### ISSUE TITLE
HTML/CSS/UI - Un-Fubar layout for Website

### ISSUE THREAD

**Issue by sethborne** [RecursiveThinking/recursive_thinking_website#70]

**Comment by sethborne** [comment]
So, I'm not saying these fixes are the best "for performance" but it handles lots of issues.  

Want to make it sexier - let me know!  :)

**Comment by MynockSpit** [comment]
Some might say you're **raising the fubar**.

**Comment by sethborne** [comment]
Ooh-rah?  :)

**Comment by MynockSpit** [comment]
Closing 'cause it works. 😁
